### ISSUE TITLE
Illustratorの型定義でgeometricBoundsがRect型だとエラーになります。

### ISSUE THREAD

**Issue by omoti-immortal** [ten-A/Types-for-Adobe#1]
Illustratorの型定義で、geometricBoundsが**Rect型**だとエラーになります。**４つの数値をもつ配列型**と思いますので、number[]にするとうまくいきます。

×　`geometricBounds: Rect;`
○　`geometricBounds: number[];`

**４つの数値**と限定する配列型にしたいのですが、できるかわかりません。

**Comment by ten-A** [comment]
In Illustrator CC 2019 Types, Replaced Rect to Array. The visibleBounds and the controlBounds also replaced.
Please, testing these properties.

**Comment by omoti-immortal** [comment]
Thank you for fixing these properties. Each is tested and works well.
Would you fix other versions as well?

**Comment by ten-A** [comment]
Thanks, Omochi.
I'll fix other versions later.
